### ISSUE TITLE
Incorrect folder with multiple languages

### ISSUE THREAD

**Issue by RiemerBug** [odoe/generator-arcgis-js-app#18]
If I add another language to includeLocales: ['en-us', 'de'] in the build.profile.js, in my case de. 
moment_de.js will load from the wrong place (outside the release folder)

**Comment by odoe** [comment]
Thanks for reporting this! I've done some local testing and I think I figured this out. I'll push a patch out today.

The fix is to update the path of the `defaultConfig`

**Comment by odoe** [comment]
oops, stupid tab

Update the paths for `defaultConfig`

``` js
  defaultConfig: {
    parseOnLoad: true,
    deps: ['app/main'],
    hasCache: {
      'extend-esri': 0,
      'dojo-has-api': 1,
      'dojo-undef-api': 0
    },
    paths: {
      'app/config': './config',
      'esri/layers/vector-tile': './vector-tile',
      'moment': './moment' // add this
    }
  }
```

It will then point the moment directory correctly.

Only problem here is that you would need to include all locales you want to support into your built app, which may not be desirable. This leads me to think I should add an option to not copy the built `dojo/dojo.js` into the `app.js` so that you could still lazy load the locales as needed.

I'll test more on that enhancement and see if I could still create the cache busted `app.js` but still have all the other files available for lazy loading.

Thanks!

**Comment by odoe** [comment]
This should be fixed here https://github.com/odoe/generator-arcgis-js-app/commit/3373558ba3dab3358e639fd020c184af093eb4ad
