### ISSUE TITLE
Switch to BrowserSync

### ISSUE THREAD

**Issue by odoe** [odoe/generator-arcgis-js-app#7]
I've been testing [grunt-browser-sync](https://browsersync.io/docs/grunt/) as a replacement for `http-server` and `livereload`. It would save the step of having to inject the `livereload` script into the page during dev and so far has been working petty well.

Will put it through a few more paces before making the change,

**Comment by tomwayson** [comment]
I'd vote for not using browser-sync, or at least be sure to test it on Windows (I can help w/ that). I've been having a lot of trouble in [other projects](https://github.com/tomwayson/angular2-esri-example) w/ browser-sync on Windows - sometimes taking up to **30 seconds** to serve a page (_after_ any transpilation, pre-processing etc has happened). Actually, I'm pretty sure I had these problems w/ http-server in test apps I built from _this_ generator too at one point (didn't we talk about that before?), but I can't reproduce them now.  

All I can say for sure is that browser-sync is unusable for me in other projects, and that I've never had any problems w/ [grunt-contrib-connect](https://www.npmjs.com/package/grunt-contrib-connect)  (which [also supports livereload](https://www.npmjs.com/package/grunt-contrib-connect#livereload) w/o manual script insertion, even on projects where we're loading local esri/dojo packages. 

If you're close on BrowserSync and want to throw up a branch/PR for me to test on Windows I can. Otherwise, would you be interested in a PR using connect-livereload instead?

**Comment by odoe** [comment]
Yeah, at this point, I think I'll leave the injected livereload script as-is. BrowserSync has been a little slower in my testing, so no changes for now.
